#First we need to decide which OS w need 
#Next we nw=ees JDK/JRE to run our JAva
#Thaen we need to feed the command to run our java code

FROM openjdk:8-jdk-alpine3.9
COPY HelloWorld.class .
CMD java HelloWorld